pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK21'
    }

    stages {

        stage('Build') {
            steps {
                dir('sampleMavenApp') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('sampleMavenApp') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('sampleMavenApp') {
                    bat 'mvn package'
                }
            }
        }
    }
}